---
- hosts: backend
  remote_user: "ubuntu"
  become: true
  gather_facts: false

  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""

  - name: Gathering Facts
    setup:

  - name: Configure NODE_ENV
    lineinfile: dest=/etc/environment regexp="^NODE_ENV=" line="NODE_ENV=production"

  roles:
    - webserver

